spring:
    application:
        name: "invoice-manager-server"
    jpa:
        hibernate:
            ddl-auto: update
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8081/auth/realms/invoice-manager-realm

management:
    endpoints:
        web:
            exposure:
                include: "*"

server:
    servlet:
        context-path: /${spring.application.name}
