spring:
    application:
        name: "invoice-manager-server"
# If you want to use PostgreSQL database, uncomment the block below and comment the H2 block
    datasource:
        url: jdbc:mariadb://localhost:3306/invoice-manager-db?createDatabaseIfNotExist=true
        username: root
        password: ${MARIADB_ROOT_PASSWORD}
    # If you want to use H2 database, comment the datasource block above and uncomment the block below
#    datasource:
#        url: jdbc:h2:file:./invoice-manager-db
#        username: sa
#        password:
#    h2:
#        console:
#            enabled: true
#            path: "/h2"
    jpa:
        hibernate:
            ddl-auto: update
### Uncomment the next line if you want to use PostgreSQL database
#        database-platform: org.hibernate.dialect.PostgreSQLDialect
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8081/auth/realms/invoice-manager-realm

management:
    endpoints:
        web:
            exposure:
                include: "*"
