spring:
    profiles:
        # Keine Security, Lege Dateien lokal ab, integrierter PDF Generator, Nutze H2 Datenbank
        active: develop,localfilestorage,standard,h2
    application:
        name: "invoice-manager-server"
    jpa:
        hibernate:
            ddl-auto: update
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8081/auth/realms/invoice-manager-realm

management:
    endpoints:
        web:
            exposure:
                include: health,info,mappings

#server:
#    servlet:
#        context-path: /${spring.application.name}

logging:
    file:
        path: logs
    level:
        net:
            tomczek: DEBUG


company:
    details:
        name: "My Company"
        street: "14 N Moore St"
        city: "New York"
        country: "USA"
        house-number: "1"
        zip-code: "10013"
        phone-number: "216 245-2368"
        email: "support@mycompany.com"
