spring:
    application:
        name: "invoice-manager-server"
    r2dbc:
# If you want to use MariaDB database, uncomment the block below and comment the H2 block
        url: "r2dbc:mariadb://localhost:3306/invoice-manager-db"
        username: "root"
        password: ${MARIADB_ROOT_PASSWORD}
    # If you want to use H2 database, comment the block above and uncomment the block below
#        url: r2dbc:h2:file:./invoice-manager-db
#        username: sa
#        password:
#    h2:
#        console:
#            enabled: true
#            path: "/h2"
    jpa:
        hibernate:
            ddl-auto: update
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8081/auth/realms/invoice-manager-realm

management:
    endpoints:
        web:
            exposure:
                include: "*"
